[project]
name = "recipe-storage"
version = "0.0.0"
description = "API app for maintaining recipe storage"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0"
]